### ISSUE TITLE
Zbytečnosti v modelu

### ISSUE THREAD

**Issue by karlosss** [frantiseksimorda/lsum#10]
Zatím to asi nevadí, ale myšlenkový postup by měl být přesně naopak - založit něco v momentě, kdy je to potřeba, a ne v momentě, kdy si řekneš, že by se to někdy v budoucnu mohlo hodit. Vyřešíme v pondělí.

**Comment by frantiseksimorda** [comment]
Uz nechlastej

**Comment by karlosss** [comment]
Chceš taky? Přivezu nějakou medovinu, když mi uděláš backup databáze.
