### ISSUE TITLE
Synchronizace z bakalářů

### ISSUE THREAD

**Issue by karlosss** [frantiseksimorda/lsum#14]
Tak se nějak pokusím shrnout naši domluvu, začnu na tom makat zítra.

Systémem, do kterého se všechno bude vyplňovat ručně, budou Bakaláři a ideálně žádný jiný. Do vstupů, kopírek a uživatelských účtů data doplní naše aplikace sama.

Teď už k samotné synchronizaci. Podle intern_kodu se zjistí, zda už tu student byl nebo ne. V případě, že se zjistí, že tu nebyl, se provede následující:
- vytvoření username a def.pwd
- vytvoření e-mailu
- vytvoření záznamu v databázi vstupů
- vytvoření záznamu na kopírkách

V případě, že už student existuje, tak nás ještě bude zajímat, jestli je aktivní nebo ne. Neaktivní student:
- nebude mít záznam v databázi vstupů
- bude mít disablovaný účet
- na kopírkách bude existovat, jako kdyby tady byl
- e-mail bych tomu chudákovi asi taky nechal - @frantiseksimorda co ty na to? Znamenalo by to, že když někdo odejde předčasně (Franěk a spol), tak bude mít školní mail, nevadí to? Není to ideální, ale daní za to by bylo, že když někdo odjede do zahraničí, tak by neměl e-mail k dispozici.

Pokud neaktivní student dojde až do oktávy a odmaturuje, tak se mu zruší e-mail, kopírky a uživatelský účet definitivně (možno nějaký delay - 1 rok - o něčem takovém jsme se bavili @frantiseksimorda?)

Aktivní student (je to asi jasný, ale pro jistotu):
- bude existovat ve vstupech, kopírkách a bude mít aktivní uživatelský účet

U učitelů bych, kromě vstupů, nemazal nic (co kdyby se vrátili?). Potřeba opět rozmyslet e-mail, jestli jim ho při odchodu sebereme (ale opět hrozí, že se učitel vrátí a po dobu nepřítomnosti nebude mít e-mail, i když tady se to podle mě dá docela dobře smazat a znova založit - nejsi zaměstnanec, nemáš e-mail, čus. @frantiseksimorda názor?)

Dále je potřeba upravit model. Ještě si rozmyslím, jak je to správně, ale prozatím by to asi vypadalo takhle:
Tabulka uživatelských účtů. Bude navázaná na intern_kod a bude obsahovat tyto položky:
- login (nový formát xPriJm01)
- defPwd (nějaký rekurzivní SHA512 hash :) )
- isActive (tinyint: 1-aktivní, 0-disabled)
- isBanned (pro neaktivní účty tinyint: 1-zabanovaný, 0-prostě vypnutý)
- banReason (asi bych ho tam taky dal, ať se těm blbečkům můžeme smát :) )
- unban (čas, kdy se účet sám odblokuje)

@frantiseksimorda názor?

dík

**Comment by karlosss** [comment]
EDIT:

(nebo spíš doplnění teda)

Samotná synchronizace bude vypadat tak, že se všechno smaže a znova naimportuje. V tabulce uživatelských účtů pak poznáme, kdo už tu byl, kdo ještě ne a kdo zmizel.

**Comment by frantiseksimorda** [comment]
Popsal si to dobře, jen pár poznámek:
exulant student (např. Franěk): email musí být neaktivní. (řešit ručně individuálně? BTW google apps má API pro Python :-) je v AURu) Ostatní jak píšeš.

isActive tam už je - active, def_pwd a login také už v modelu existují.  Ale můžeš to upravit, stejně jako další části modelu.

Kantoři - ano, často se vrací a to nejen ženy z mateřské, proto by bylo fajn je jen "vypínat", a při tom zrušit i email.
