### ISSUE TITLE
Po vygenerovani novych loginu, potrebuji jejich export

### ISSUE THREAD

**Issue by frantiseksimorda** [frantiseksimorda/lsum#17]
tzn. potrebuji jednoznacne poznat ktere jsou nove. V administraci v tabulce user_account_student neni sloupek, podle ktereho bych to pozna (PS: nemusi to byt jen prvaci, napr. prestup).

**Comment by karlosss** [comment]
A řekneš mi, co je to nový login? Vygenerovaný při posledním generování nějakých loginů? Nebo vygenerovaný při poslední synchronizaci? Nebo mladší než určité datum? Jinak souhlasím, že tohle tam není.

**Comment by frantiseksimorda** [comment]
Vygenerovany pri poslednim generovani.

**Comment by karlosss** [comment]
bude řešit skript na serveru, my to můžem mít v piči, prozatím close
