### ISSUE TITLE
Správa čipů - učitelé

### ISSUE THREAD

**Issue by karlosss** [frantiseksimorda/lsum#19]
Dodělat volby pro učitele - wizard pro přiřazení všem, dále dodělat listboxový výběr jednotlivých osob ve správě čipu, poté přidat wizarda pro vybrání jednotlivého učitele.

**Comment by karlosss** [comment]
zároveň ve wizardu přiřazování novým studentům (učitelům) přidat možnost přeskočení aktuálního studenta

**Comment by frantiseksimorda** [comment]
Souhlasí. 

BTW možnost odebrání čipu musí fungovat mezi skupinami (kantoři X studenti)

**Comment by karlosss** [comment]
To by neměl být problém, ve správě čipu prostě bude další formulář - combobox, obsahující seznam učitelů.
