### ISSUE TITLE
Vytvořit databázi pro vytváření uživatelů

### ISSUE THREAD

**Issue by frantiseksimorda** [frantiseksimorda/lsum#21]
Django by jí mělo plnit, skript na generování userů do ní vidět a změnit u každého nějaký BOOL vygenerovano=1
Ke generování bude potřeba - login, password, vygenerovano, student/kantor 
(Vygenerovano by mohlo byt i v tabulce user_account_student?)

**Comment by karlosss** [comment]
Viděl bych to takhle:

do externí databáze by se zapisoval příkaz a argumenty, se kterými se příkaz má vykonat. Strukturu bych viděl asi takhle:
- příkaz (create, enable, disable, delete)
- username
- password (nepovinné, povinné jen pro create)
- typ (student, učitel)
- doba provedení příkazu (při scanování databáze se provedou jen ty příkazy, které mají starší unixtime než aktuální - využití třeba typicky při auto unbanu - delayed enable nebo pro smazání maturanta po roce - delayed delete)
- provedeno (asi bych nedělal jenom bool, ale dal bych int - možnosti 0-neprovedeno, 1-provedeno, 2+ neprovedeno, protože se něco posralo - možnost chybových kódů)

Dá se změnit uživatelské jméno existujícího účtu?
