### ISSUE TITLE
Index Error při synchronizaci v případě, že má uživatel otevřený formulář

### ISSUE THREAD

**Issue by karlosss** [frantiseksimorda/lsum#24]
Teoreticky se může stát napřklad toto:

- uživatel si klikne na správu jednotlivého studenta ve správě čipů
- proběhne synchronizace, zmizí 120 maturantů z databáze
- uživatel vybere jednoho z těch zmizivších maturantů s tím, že s ním chce pracovat, odešle formulář
- vyhodí to IndexError, protože ten vybraný student právě zmizel z databáze

Je to šance asi tak 1 ku miliónu a asi ještě míň, navíc moc nedává smysl, že by se někdo chtěl vrtat ve studentech, co to už nejsou, ale stejně by se to mělo nějak vyřešit. Máme tři možnosti:

- vysrat se na to a nechat to s tím, že občas může přijít Internal Server Error (v reálu pak stačí obnovit stránku, aby se znova vytvořily seznamy dle databáze)
- při synchronizaci vždy obnovit aktuální stránku (Django by to možná mohlo umět) - taková čuňárna, ale asi to bude fungovat, nevýhoda je, že uživatel přijde o vyplněné formuláře
- vymyslet to nějak lépe a ošetřit tuhle konkrétní výjimku (vyhodit něco jako "student již neexistuje") a poté vytvořit nový formulář

Osobně jsem zatím pro možnost číslo jedna, až potom dospějeme do fáze, kdy budeme psát styly k jednotlivým stránkám, tak bych se na to kdyžtak kouknul.

@frantiseksimorda ?

**Comment by frantiseksimorda** [comment]
jasne, casem. Nekdrive musime vyresit studenty a generovani loginu a uctu

**Comment by frantiseksimorda** [comment]
Asi nema smysl resit
