### ISSUE TITLE
Skript a správa účtů vůbec

### ISSUE THREAD

**Issue by karlosss** [frantiseksimorda/lsum#25]
Včera to vypadalo, že si úplně nerozumíme, tak to tady zkusím nějak rozepsat.

Celé udělátko má několik částí. První část (a taky ta jediná, co nutně musí běžet pod rootem) se chová následovně:
- z databáze vycucne příkaz (celý napsaný tak, jako kdybys ho psal ručně do konzole)
- provede ho (tak, jako kdybys stisknul enter)
- do databáze zapíše timestamp, jak to dopadlo, a k tomu ještě pokud možno celý stderr, co to vyhodí - přece to nějak musí jít

Tady rovnou první dotaz: pokud se do toho někdo nabourá, tak nám do databáze zapíše "rm -rf /" a jsme v piči. Proto bych možná zkusil nějaký enum (asi bude docela sranda zjistit, jak se to v Django modelech dělá, ale nějak to půjde) nebo aspoň kontrolu v této vrstvě s tím, že skript pustí pouze příkazy useradd a smbpasswd, zbytek bude ignorovat. Do seznamu povolených se dá kdykoli cokoli dopsat, kdyby se zjistilo, že to potřebujeme. Taky bych ještě z bezpečnostních důvodů zakázal středník. @frantiseksimorda ?

Další části už potom můžou běžet pod Djangem. 

Druhá část: Engine na příkazy bude zjišťovat, jaké loginy jsou vygenerovány, ale nevytvořeny, jaké účty jsou určeny k zabanování, ale zatím ještě nezabanovány apod., bude tvořit unixové příkazy a zapisovat je do databáze, aby je skript mohl vykonat.

Třetí částí je potom databáze, která obsahuje informace o účtech. Zde je u každého účtu true/false, zda je aktivní, jeho uživatelské jméno a podobně. Tohle už máme navrženo, ale ještě to nefunguje. Vezmu si to na starost já, tobě bych nechal ty první dvě části, jestli tomu teda nějak rozumíš. Ta první je na 10 minut, ta druhá už asi nějakou chvilku zabere.

@frantiseksimorda ?

**Comment by frantiseksimorda** [comment]
Tak me napada, prikaz (prikazy) bych dal do generovaciho skriptu a do tabulky jen ukladat priznak cinnosti (add, del, disable, enable, create_user)
To bude lepsi i logictejsi, nejaky if rozhodne co se bude delat a argumenty jsou na pul tabulce a z druhe pulky jsou danne akci, kterou chces vykonat.

**Comment by karlosss** [comment]
tak jako v zásadě je to asi jedno, chtěl jsem tomu skriptu akorát co nejvíc odlehčit, tohle by asi taky mělo jít

**Comment by frantiseksimorda** [comment]
Téměř hotovo

**Comment by karlosss** [comment]
Tak doufám, že se nějak potkáme v tom, co máme na mysli, zrovna jsem to chtěl psát.

Je potřeba myslet na to, že neděláš skript, ale modul. To jsem se snažil říct už v pátek. Zkusím to ještě trochu popsat, co to vlastně je.

- samo o sobě by to při spuštění (importu) nemělo mimo nějakých importů, případně načtení a výpočtu věcí vitálních pro běh některých funkcí dělat vůbec nic
- s tím souvisí, že vše je ve funkcích/třídách
- asi nejdůležitější je, že to píšeš pro někoho jiného - můsí to být univerzální

Poslední bod mimo jiné znamená, že čtení/zápis do konkrétní tabulky je na nic. Proč jsem to takhle dříve chtěl jsem ti říkal - věřil jsem, že skripty poběží dva. Když ale bude jeden, tak tohle postrádá smysl.

Příklad funkce modulu:
```python
def createUnixUser(username, password, name, surname, type):
    #vytvoř uživatele v unixu podle parametrů
    return (stdout, stderr)
```
Jestli máš nějaké poznámky, případně dotazy, cokoli, tak napiš, dík.

**Comment by frantiseksimorda** [comment]
Takze tabulka script se zrusi?

**Comment by karlosss** [comment]
V ideálním případě jo, jestli do ní hodně moc chceš zapisovat ten log, tak to asi nevadí.

Inspiraci kdyžtak můžeš hledat v connection.py (tam je to úplně čistý) nebo v login_generator.py (tam si ale nepamatuju, v jakým je to stavu, tam se možná někde prasí :) )
