### ISSUE TITLE
SafeQ sync

### ISSUE THREAD

**Issue by frantiseksimorda** [frantiseksimorda/lsum#29]
Pokus se prosim take udelat do synchronizace pridani do SafeQ, jak najdes v mem super .py souboru, kde se ti nelibil zpusob pripojovani k DB
Aby melo nejaky smysl mit cipy s lsumu

**Comment by karlosss** [comment]
ok

ps: dávej tomu prosím tagy

**Comment by frantiseksimorda** [comment]
roger roger
