### ISSUE TITLE
jmeno?

### ISSUE THREAD

**Issue by frantiseksimorda** [frantiseksimorda/lsum#30]
Nedozral cas tak daleko, ze bychom meli projek prejmeovat z pracovni zkratky na jmeno? (mozna ne)

**Comment by karlosss** [comment]
lsum není konečné jméno? :(

**Comment by frantiseksimorda** [comment]
Může, ale nemusí.

**Comment by karlosss** [comment]
Tady asi speciální požadavky nemám, nesnáším pojmenovávání čehokoli :)
