### ISSUE TITLE
novy useri v SafeQ maji asi empy string v cipu

### ISSUE THREAD

**Issue by frantiseksimorda** [frantiseksimorda/lsum#32]
V administraci maji vyplneny cip, ale jeho hodnota je neco jako empy string, zkusit nahrat policko NULLem?

**Comment by karlosss** [comment]
UPDATE users_cards SET card=NULL where card=""

stačilo by v rámci syncu?

**Comment by frantiseksimorda** [comment]
No spis bych jim pri zakladani vlozil NULL rovnou a ne teď dodatečně

**Comment by frantiseksimorda** [comment]
Přidání čipu to hezky změní, takže to není problém.
