### ISSUE TITLE
Export (import) v tabulce studenti

### ISSUE THREAD

**Issue by frantiseksimorda** [frantiseksimorda/lsum#33]
ten potřebujeme např. kvůli eurestu - student,třída,čip ...

**Comment by frantiseksimorda** [comment]
Eurest chce jeste datum narozeni :-( skoro bych ho importoval take

**Comment by frantiseksimorda** [comment]
ok, tak uz jen upravit format - jmeno,prijmeni,trida,dataum_narozeni (idealne format 11.22.3333),cip

**Comment by frantiseksimorda** [comment]
+ login!

**Comment by karlosss** [comment]
datum narození máme YYYY-MM-DD, posere se z toho eurest? otherwise mám hotovo

**Comment by frantiseksimorda** [comment]
nevadi cokli, jen kdyz tam to policko bude ...

**Comment by karlosss** [comment]
jako asi není problém ten string přeformátovat, ale lenost zatím vyhrávala :D
